development:
  adapter: postgresql
  database: receta_development
  host: localhost
  username: rgpass
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: receta_test
  pool: 5
  username: rgpass
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: receta_production
  pool: 5
  username: receta
  password:
